### ISSUE TITLE
Make default repos the users watched repos

### ISSUE THREAD

**Issue by megawac** [notwaldorf/frankly#1]
For example https://api.github.com/users/megawac/subscriptions or https://api.github.com/users/notwaldorf/subscriptions

**Comment by notwaldorf** [comment]
That's a great idea, thank you!

**Comment by notwaldorf** [comment]
@megawac Done! for this case, the syntax will be just

```
<frank-ly labels='["bug", "enhancement"]'></frank-ly>
```

(and the `header`, of course, if you want it). 
🎉

**Comment by megawac** [comment]
noice  :confetti_ball:
