### ISSUE TITLE
GitHub application name: "Grilled Cheese"

### ISSUE THREAD

**Issue by cllns** [notwaldorf/frankly#4]
Thanks for making this, it's awesome!

When I authenticated with GitHub, it said the name of the app is "Grilled Cheese", not "Frankly".

Not sure if that's intentional or not :)

**Comment by notwaldorf** [comment]
Hah, that's the name of the firebase app that does the oauth. I guess I should change it!

**Comment by notwaldorf** [comment]
Whew, fixed! Thanks for catching this!

**Comment by cllns** [comment]
You're welcome! Looks good on my end too :+1: 
![screen shot 2016-02-12 at 15 19 01](https://cloud.githubusercontent.com/assets/632942/13022045/f98fdbb4-d19b-11e5-9bc3-8fb5af985b4c.png)

**Comment by notwaldorf** [comment]
Goes to show you shouldn't test with dumb names 😊

**Comment by cllns** [comment]
I wanted to use a grilled cheese emoji but it doesn't exist :'(

**Comment by notwaldorf** [comment]
🔥🍞🧀
