### ISSUE TITLE
Broken links with 'organization'

### ISSUE THREAD

**Issue by cllns** [notwaldorf/frankly#5]
When I set up Frankly as follows:

```
<frank-ly header="🚂🚃🚃💨"
  organization="hanami"
  repos='["model", "view"]'
  labels='["bug", "enhancement"]'>
```

It creates the links as `hanami/hanami/model` rather than just `hanami/model`. This is both in the visible link, and the `href`, so the link doesn't work. Interestingly, it pulls the stats correctly still.
![screen shot 2016-02-12 at 15 07 43](https://cloud.githubusercontent.com/assets/632942/13021848/9858f912-d19a-11e5-8715-5dbcb2e52a37.png)

When I use `full-repo-names` it works fine!

**Comment by notwaldorf** [comment]
Oops! Fixed in a52250177e11779. Thanks for spotting this! 😳
